# Generated by Django 6.0.1 on 2026-01-21 02:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to='incidentes/'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['estado'], name='incidentes__estado__a8ffcc_idx'),
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['fecha_creacion'], name='incidentes__fecha_c_b13c4e_idx'),
        ),
    ]
