# Generated by Django 6.0.1 on 2026-01-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_incidente_evidencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='incidente',
            name='latitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='incidente',
            name='longitud',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
