# Generated by Django 6.0.1 on 2026-01-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0004_auditoriaaccion'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='incidente',
            name='incidentes__estado__a8ffcc_idx',
        ),
        migrations.RemoveIndex(
            model_name='incidente',
            name='incidentes__fecha_c_b13c4e_idx',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='fecha_borrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incidente',
            name='fecha_borrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fecha_borrado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
