# Generated by Django 6.0.1 on 2026-01-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0005_remove_incidente_incidentes__estado__a8ffcc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='capacidad',
            field=models.TextField(),
        ),
    ]
