# Generated by Django 6.0.1 on 2026-01-22 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0006_alter_recurso_capacidad'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='rescatista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_asignados', to=settings.AUTH_USER_MODEL),
        ),
    ]
